apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-stack-ingress
  namespace: mongo-stack
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: mongoapp.local
    http:
      paths:
      - path: /mongo-express
        pathType: Prefix
        backend:
          service:
            name: mongo-express
            port:
              number: 80
