apiVersion: batch/v1
kind: Job
metadata:
  name: init-mongo-replicaset
  namespace: mongo-stack
spec:
  template:
    spec:
      containers:
      - name: mongo-init
        image: mongo:6.0
        command: ["mongo"]
        args: [
          "--host", "mongodb-0.mongodb-headless.mongo-stack.svc.cluster.local:27017",
          "--eval",
          "rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'mongodb-0.mongodb-headless.mongo-stack.svc.cluster.local:27017'}, {_id: 1, host: 'mongodb-1.mongodb-headless.mongo-stack.svc.cluster.local:27017'}, {_id: 2, host: 'mongodb-2.mongodb-headless.mongo-stack.svc.cluster.local:27017'}]})"
        ]
      restartPolicy: OnFailure
